apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 533616270150.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 533616270150.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: 3c794f66
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
